#!/usr/bin/env python
import argparse
import requests
import json
import pprint
 

def doanswer(ar):
    url_call='http://localhost:5000/doanswer/{}/{}/{}/{}'.format(ar.questionnaire_id,ar.question_id,ar.session_id,ar.option_id)
    res = requests.post(url_call)
    print(res.status_code)
    return True


parser = argparse.ArgumentParser()
parser.add_argument('--questionnaire_id', help='Give questionnaire_id of the question', required='TRUE')
parser.add_argument('--question_id', help='Give question that you want to answer', required='TRUE')
parser.add_argument('--session_id', help='Give the session number', required='TRUE')
parser.add_argument('--option_id', help='Pick Option', required='TRUE')
args = parser.parse_args()

doanswer(args)