#!/usr/bin/env python
import argparse
import requests
import json
import pprint
 

def getsessionanswers(ar):
    url_call='http://localhost:5000/getsessionanswers/{}/{}'.format(ar.questionnaire_id,ar.session_id)
    res = requests.get(url_call)
    print(res.status_code)
    print(json.dumps(res.json(),ensure_ascii=False,indent=2))
    return True


parser = argparse.ArgumentParser()
parser.add_argument('--questionnaire_id', help='Give questionnaire_id', required='TRUE')
parser.add_argument('--session_id', help='Give session that you want to receive answers', required='TRUE')
parser.add_argument('--format', help='Give response format', required='TRUE')
args = parser.parse_args()

getsessionanswers(args)