#!/usr/bin/env python
import argparse
import requests
import json
import pprint

def healthcheck(ar):
    url_call='http://localhost:5000/admin/healthcheck?format={}'.format(ar.format)
    res = requests.get(url_call)
    print(res.status_code)
    print(res.text)
    return True

parser = argparse.ArgumentParser()
parser.add_argument('--format', help='Give response format', required='TRUE')
args = parser.parse_args()

healthcheck(args)