#!/usr/bin/env python
import argparse
import requests
import json
import pprint
 

def questionnaire(ar):
    url_call='http://localhost:5000/question/{}/{}'.format(ar.questionnaire_id,ar.question_id)
    res = requests.get(url_call)
    print(res.status_code)
    print(json.dumps(res.json(),ensure_ascii=False,indent=2))
    #print(json.dumps(res.json(),ensure_ascii=False).encode('utf-8'))
   # with open('new.txt','w+',encoding='utf-8') as f:
    #    json.dump(res.json(),f,ensure_ascii=False)
    return True


parser = argparse.ArgumentParser()
parser.add_argument('--questionnaire_id', help='Give questionnaire_id', required='TRUE')
parser.add_argument('--question_id', help='Give question_id that belongs to the questionnaire', required='TRUE')
parser.add_argument('--format', help='Give response format', required='TRUE')
args = parser.parse_args()

questionnaire(args)