#!/usr/bin/env python
import argparse
import requests
import json
import pprint
 

def questionnaire(ar):
    url_call='http://localhost:5000/questionnaire/{}'.format(ar.questionnaire_id)
    res = requests.get(url_call)
    print(res.status_code)
    pprint.pprint(res.json())
    return True


parser = argparse.ArgumentParser()
parser.add_argument('--questionnaire_id', help='Give questionnaire_id to see info', required='TRUE')
args = parser.parse_args()

questionnaire(args)